SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS Suscriptions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  value VARCHAR(255) NOT NULL,
  time VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Allys (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dni VARCHAR(255) NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  commerce_name VARCHAR(100) NOT NULL,
  mail VARCHAR(100) NOT NULL,
  commerce_type VARCHAR(100) NOT NULL,
  suscription INT,
  FOREIGN KEY (suscription) REFERENCES Suscriptions(id)
);
  
COMMIT;